In [46]:
pip install imbalanced-learn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: imbalanced-learn in c:\programdata\anaconda3\lib\site-packages (0.10.1)
Requirement already satisfied: numpy>=1.17.3 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (1.24.3)
Requirement already satisfied: scipy>=1.3.2 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (1.10.1)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (1.3.0)
Requirement already satisfied: joblib>=1.1.1 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

In [47]:
import pandas as pd

In [48]:
# Loading the dataset

# df = pd.read_csv('cleaned_framingham.csv')

In [49]:
df=pd.read_csv('machine')

In [50]:
pip install imbalanced-learn

Defaulting to user installation because normal site-packages is not writeableNote: you may need to restart the kernel to use updated packages.

Requirement already satisfied: imbalanced-learn in c:\programdata\anaconda3\lib\site-packages (0.10.1)
Requirement already satisfied: numpy>=1.17.3 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (1.24.3)
Requirement already satisfied: scipy>=1.3.2 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (1.10.1)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (1.3.0)
Requirement already satisfied: joblib>=1.1.1 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from imbalanced-learn) (2.2.0)

In [73]:
from imblearn.over_sampling import SMOTE

ImportError: cannot import name '_MissingValues' from 'sklearn.utils._param_validation' (C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py)

In [ ]:
df.head(3)

In [ ]:
# Check dataset information
df.info()

# Creating `X-input` and `y-output`

In [ ]:
df.head()

In [ ]:
X  = df.drop(columns=['TenYearCHD'], axis=0)
y = df.TenYearCHD

In [ ]:
X.head()

# Spliting our data into Training and Testing

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=.20, random_state=42)
# train_test_split()

In [ ]:
# Checking the shape of the `X_train`,`X_test`, `y_train` and `y_test`

print("X_train shape: ",X_train.shape)
print("X_test shape: ",X_test.shape)
print("y_train shape: ",y_train.shape)
print("y_test shape: ",y_test.shape)

# TRAINING THE MACHINE LEARNING MODEL

In [1]:
# DECISION TREE CLASSIFIER
dtc = DecisionTreeClassifier()

NameError: name 'DecisionTreeClassifier' is not defined

In [ ]:
dtc.fit(X_train,y_train)

# MODEL EVALUATION

In [ ]:
dtc.score(X_test, y_test)

In [ ]:
# Predicting with the model
# Predictions are stored in y_pred
y_pred = dtc.predict(X_test)

In [ ]:
# Comparing model predicted values and actual values

print('array:',y_test[:25].to_list())
y_pred[:25]

# PLEASE USE THIS METHOD YOU'LL ALWAYS MEET IT

In [52]:
# Training Accuracy

dtc.score(X_train,y_train)

1.0

In [53]:
# TESTING ACCURACY

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.75

In [54]:
confusion_matrix(y_test,y_pred)

array([[613, 112],
       [100,  23]], dtype=int64)

In [55]:
(23+613)/(613+112+100+23)

0.75

In [56]:
#PRECISION

precision_score(y_test,y_pred) # when it predict yes how often is it correct

0.17037037037037037

In [57]:
# RECALL

recall_score(y_test,y_pred)#When it's actually yes, how often does it predict yes

0.18699186991869918

In [58]:
X_train.head(5)

,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,age
1427,3,1,20.0,0.0,0,0,0,221.0,131.0,89.0,24.09,90.0,95.0,53
3257,4,1,6.0,0.0,0,1,0,239.0,143.0,84.0,20.06,55.0,73.0,64
3822,3,0,0.0,0.0,0,0,0,185.0,100.0,72.0,22.15,85.0,83.0,38
1263,1,0,0.0,0.0,0,0,0,263.0,126.5,67.5,26.56,70.0,77.0,49
3575,2,1,20.0,0.0,0,0,0,186.0,116.0,67.0,24.62,70.0,83.0,56

In [59]:
X_train.totChol.describe()

count    3392.000000
mean      229.782134
std        31.396918
min       107.000000
25%       207.000000
50%       235.000000
75%       263.000000
max       263.000000
Name: totChol, dtype: float64

In [60]:
scaler = MinMaxScaler()
pd.DataFrame(scaler.fit_transform(X_test))

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.666667,1.0,0.166667,0.0,0.0,0.0,0.0,0.980000,0.550000,0.345679,0.187662,0.220930,0.060000,0.444444
1,0.000000,1.0,0.416667,0.0,0.0,0.0,0.0,0.586667,0.516667,0.370370,0.208994,0.302326,0.134286,0.277778
2,0.000000,1.0,0.016667,0.0,0.0,1.0,0.0,1.000000,0.833333,0.395062,0.350245,0.290698,0.085714,0.333333
3,0.666667,1.0,0.166667,0.0,0.0,1.0,0.0,0.820000,1.000000,0.629630,0.326319,0.186047,0.085714,0.833333
4,0.333333,0.0,0.000000,0.0,0.0,0.0,0.0,0.826667,0.691667,0.395062,0.218507,0.534884,0.142857,0.722222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
843,0.666667,1.0,0.250000,0.0,0.0,0.0,0.0,0.553333,0.291667,0.179012,0.174402,0.011628,0.100000,0.055556
844,0.666667,1.0,0.500000,0.0,0.0,0.0,0.0,0.646667,0.708333,0.407407,0.346786,0.279070,0.074286,0.222222
845,0.000000,0.0,0.000000,0.0,0.0,1.0,0.0,1.000000,1.000000,0.654321,0.327760,0.360465,0.122857,0.833333
846,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,1.000000,0.566667,0.253086,0.220525,0.558140,0.122857,0.333333
847,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.740000,0.300000,0.172840,0.345344,0.534884,0.151429,0.166667

In [64]:
cross_validate(dtc, X, y, cv=10, scoring='accuracy') #cross validationwill pick the data frame 10 1,use the first data set to train then the other to test

{'fit_time': array([0.16590118, 0.12499452, 0.14061809, 0.12499213, 0.12499189,
        0.12514567, 0.14046526, 0.18502116, 0.1353972 , 0.14234304]),
 'score_time': array([0.00806761, 0.        , 0.        , 0.01562667, 0.        ,
        0.        , 0.01132059, 0.0083921 , 0.        , 0.01298046]),
 'test_score': array([0.73113208, 0.77830189, 0.72877358, 0.73584906, 0.75471698,
        0.73820755, 0.73349057, 0.75943396, 0.73820755, 0.78537736])}

In [65]:
cross_validate(dtc, X, y, cv=10, scoring='accuracy')['test_score'].mean() #checkin the avearge eam of the test score

0.7537735849056604

In [66]:
df.head()

,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD,age
0,4,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0,39
1,2,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0,46
2,1,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0,48
3,3,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1,61
4,3,1,23.0,0.0,0,0,0,263.0,130.0,84.0,23.10,85.0,85.0,0,46

In [67]:
df.shape

(4240, 15)

In [68]:
df.TenYearCHD.value_counts()

0    3596
1     644
Name: TenYearCHD, dtype: int64

In [69]:
print(X_train.shape)
print(y_train.shape)

(3392, 14)
(3392,)

In [70]:
y_train.value_counts()

0    2871
1     521
Name: TenYearCHD, dtype: int64

# RESAMPLING THE IMBALANCED DATA

In [71]:
# Instantiate the function
smot = SMOTE()

# Do a fit_resample method
X_train_sm, y_train_sm = smot.fit_resample(X_train, y_train)

NameError: name 'SMOTE' is not defined

In [ ]:
# Check  the shapes to make sure

print(X_train_sm.shape)
print(y_train_sm.shape)

In [ ]:
y_train_sm.value_counts()

In [ ]:
print(X_train.shape)
print(X_train_sm.shape)

In [ ]:
dtc.fit(X_train_sm, y_train_sm)

In [ ]:
dtc.score(X_test, y_test)

In [ ]:
y_predsm = dtc.predict(X_test)

In [ ]:
confusion_matrix(y_test, y_predsm)

In [ ]:
dtc.predict_proba(X_train)

In [ ]:
from sklearn.impute import SimpleImputer, KNNImputer

In [ ]:
df0 = pd.read_csv('new_framingham.csv')

In [ ]:
df0.isnull().sum()

In [ ]:
imput = SimpleImputer(strategy='median')

In [ ]:
df0['glucose']=imput.fit_transform(df0[['glucose']])

In [ ]:
df0['glucose'].isnull().sum()